name: Docker Build

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/lullahharsh/my-portfolio:latest .

      - name: Push Docker image
        run: docker push ghcr.io/lullahharsh/my-portfolio:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/lullahharsh/my-portfolio:latest
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            docker run -d --name portfolio-container -p 80:80 ghcr.io/lullahharsh/my-portfolio:latest